### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by chrisallenlane**
Performed an app-wide refactoring in order to accomplish the following:

- Remove unnecessary indirection and abstraction
- Reorganize the `Util` class, which had become a "junk drawer"
- Use more consistent vocabulary throughout the app
- Rename envvars to be more self-descriptive
- Make the code more idiomatic to Python (and less like functional programming)
- Improve code readability in general
- Integrate a linter (`flake8`)

### CODE REVIEW

**Comment by chrisallenlane** [comment]
@pirat89 @TomasKorbar @bernermic

This is a large refactoring of the application, primarily intended to reduce abstraction and improve code-cleanliness. It should make it easier/faster for us to implement some of the remaining work to be done in the near-term.

I tested this locally, but wouldn't mind some more eyes on these changes, as there's quite a lot being re-written here.

If you all have the time, would you please confirm that none of the changes here break your builds? I tried not to change any of the external interfaces (and I _think_ I succeeded in doing so), but I don't want to break any of your packages.

**Comment by chrisallenlane** [comment]
@TomasKorbar, I'll note and apologize for the fact that I borked all of your unit-tests here. I'll update them (and add new tests) in a future PR.

**Comment by bernermic** [comment]
@chrisallenlane I included this refactor branch in the snap build pipeline.
To me all looks fine.
To test this everyone can call `sudo snap install --candidate cheat` or `sudo snap refresh --candidate cheat` ...

Also this first version of v2.4.2.build.3 is successfuly build and released (forvia the repository https://github.com/cheat/snap

**Comment by TomasKorbar** [comment]
Hi,
@chrisallenlane I've rebuild the rpm package from this branch and everything works as expected.
I dont think this change will cause any problems but still thanks for info.

**Comment by chrisallenlane** [comment]
@bernermic , @TomasKorbar 

Perfect, guys. Thanks for the feedback. I'll go ahead and merge.

**Pull request merged**
