### PR TITLE
adding the cheat autocomplete script back :)

### PR DESCRIPTION
**Pull request by zhujian0805**

### CODE REVIEW

**Comment by MadeOfMagicAndWires** [comment]
This would be hugely appreciated, since not all of us use fzf.

**Comment by chrisallenlane** [comment]
Alright - stupid question time:

I never actually got autocompletion working previously on my own machine. How are you folks "deploying" this code? Are you manually appending this function to `~/.bashrc`? Or copying this file to `/etc/bash_completion.d`? Or something else?

I very briefly skimmed some documentation regarding autocompletion the other day, but don't have any experience implementing it. Feel free to share some pro-tips here :slightly_smiling_face: 

Anyway, shell integration is the highest priority now, so expect to see some releases over the next few days that address this.

**Comment by TomasKorbar** [comment]
In Fedora we deploy bash completion script by installing it into `/usr/share/bash-completion/completions`
But you need to have installed bash-completion package first for it to work, because bash itself does not provide the completion script out of the box. Bash-completion package installs bash-completion.sh script into profile.d and that script loads necessary completion code on startup of bash.
Individual completion scripts for each command are then executed when they are needed.
I hope that puts some light on this:)

**Comment by sevens-ef** [comment]
For a user install (inside my home dir) of completion scripts, I put the completion files in `${XDG_DATA_HOME}/bash-completion/completions/` (which defaults to `~/.local/share/bash-completion/completions/`).  This is supported by bash-completion out of the box (running version 2.8 here).  For system-wide installs, see @TomasKorbar's response

**Comment by exploide** [comment]
Additionally to what @TomasKorbar explained, the process is similar for the other shells. The completion files just need to go into the respective directories and will work immediately:

```
/usr/share/bash-completion/completions/cheat
/usr/share/zsh/site-functions/_cheat
/usr/share/fish/vendor_completions.d/cheat.fish
```

Just with different naming conventions.

(Besides, a similar mechanism exists to make package specific functions available. For example there is the `/usr/share/fish/vendor_functions.d` directory. But I don't know about respective directories for bash or zsh.)

**Comment by chrisallenlane** [comment]
@zhujian0805 

Sorry for the delay merging this - I had to research a bit. I'm merging this now without changes.

@TomasKorbar @sevens-ef @exploide 

Thanks for the information. That context was very helpful in figuring this stuff out.

I guess there's no point in cutting a new `cheat` release with this, given that this does not get compiled into the binary. The shell completions are now available for packaging upstream, though.

Closing as resolved.

**Pull request merged**
