### PR TITLE
Add vendor files for go build

### PR DESCRIPTION
**Pull request by chenrui333**
Since now we have go modules build, it would nice to also include `vendor/` for the go build.

generated by `go mod vendor`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/45619

**Comment by chrisallenlane** [comment]
Thanks for this.

FYI, I also [modified the build scripts][1] to only use the vendored modules. I don't know if you use these scripts as part of your packaging process, but they're available if you need them.

Side note: thanks for your work maintaining the Homebrew formula as well!

[1]: https://github.com/cheat/cheat/commit/a13ad992416c9054ff078bcf12a7cab721de01a9

**Comment by chenrui333** [comment]
👍 

> Side note: thanks for your work maintaining the Homebrew formula as well!

My pleasure :smi'

**Comment by chenrui333** [comment]
build scripts change looks good!

**Pull request merged**
