### PR TITLE
Enable starting the cheat python script on windows.

### PR DESCRIPTION
**Pull request by aroonav**
For this add a small batch script in the same directory as the
cheat script.
This should help in resolving #305

### CODE REVIEW

**Comment by Almenon** [comment]
Thanks for attempting to fix this :) Unfortunately the script does not work on my computer. For starters, you need to wrap your paths in quotes because %PATHOFPYTHON% might have a space in it.  For example, my %PATHOFPYTHON% is C:\Program Files\Python36\python.exe\

Second of all, there's no point in getting the path of python if you are already assuming that you can access python via "python".

Third of all, you're assuming that the user has cheat installed in the Scripts directory of the python installation folder. It could be that the user installed cheat via the --user option.

Here's a working† script:

```batch
@echo off

REM %~dp0 is black magic for getting directory of script
python %~dp0\cheat %*
```

† working on my computer - @aroonav can you please test this on yours?

**Comment by aroonav** [comment]
Yup, your script works on my system.
Thanks for correcting the glaring issues 😃 

Just one comment. As %~dp0% already has a backslash at the end, we can write
```
python %~dp0cheat %*
```
instead of
```
python %~dp0\cheat %*
```
Both of the above work just fine so there's no difference in the functionality.

**Comment by chrisallenlane** [comment]
Thanks for this, guys. I should be able to merge these in after #422 lands (which should be soon).

**Comment by chrisallenlane** [comment]
@aroonav, @Almenon, @rsrini7 

I'm taking a closer look at this thread now.

I see the discussion in the comments, but I don't see that any new commits have been added to the PR. I've tried to consolidate the remarks myself, but I don't know enough (or anything) about scripting on Windows to do so.

Does somebody want to take what we've learned here and update this pull-request (or issue a new one)? I can merge this in as soon as we get this sorted out.

Thanks.

**Comment by aroonav** [comment]
@chrisallenlane I have updated the above PR and incorporated the above comments.

@Almenon @rsrini7 
Notepad does not handle UNIX line endings of the cheats very nicely. If I use notepad to edit an existing cheat, then the entire cheat file is shown in a single line. So I don't think we should use it as the default editor on windows.

We should only fall back to an editor if EDITOR, CHEAT_EDITOR and VISUAL all aren't defined.
I am using the wordpad application (`write` command) as the default application if the above environment variables aren't defined. It can handle UNIX line endings without any issues.

**Comment by chrisallenlane** [comment]
Thanks, guys.

I'm still unfortunately unable to test this myself, but it seems like we've reached a consensus here, so I merged this in. Thanks very much for the help, @aroonav, @Almenon, and @rsrini7.

**Pull request merged**
