### PR TITLE
wip(installer): stubs experimental installer

### PR DESCRIPTION
**Pull request by chrisallenlane**

### CODE REVIEW

**Comment by bernermic** [comment]
First glance over the codechanges looks good to me. I'll do a test in the snap version and the pure version soon.

**Comment by chrisallenlane** [comment]
Thanks, @bernermic. I'll need to append a few commits to this PR before it's ready to ship, so there's no urgency in testing it. I just wanted to get your eyes on it for a general 👍 / 👎  on the approach. It sounds like we're on the same page, though.

Thanks! I'll request your review again when this guy is actually ready to merge 🙂

**Comment by chrisallenlane** [comment]
Known-issue: default YAML configs will only coincidentally (at best) be correct on Unix systems. This will not be ready for merging until the configs are informed by the installation process.

**Comment by chrisallenlane** [comment]
Looks like I also broke some tests. Whoops.

**Comment by chrisallenlane** [comment]
Remember to:
- Fix the known-issue above
- Update the `README`
- Include https://github.com/cheat/cheat/pull/541 in the `3.7.0` release

**Comment by chrisallenlane** [comment]
@bernermic, please take a look now when you have a moment. At this point, I'm pretty happy with this. This should provide our users with a very pleasant and usable configuration out-of-the-box with zero manual configuration.

Please let me know if you'd like to see anything changed. Otherwise, I'll plan on cutting a new release in the near-term. Thanks!

**Comment by chrisallenlane** [comment]
FYI, this is the `3.7.0` release candidate. (I'm going to close this draft PR when we're all finished looking at it.)

https://github.com/cheat/cheat/pull/543

**Comment by chrisallenlane** [comment]
Released with `3.7.0`. Closing draft PR.

**Comment by chrisallenlane** [comment]
@bernermic, I went ahead and released this, because I'm pretty confident that you'll like this implementation. That said, by all means feel free to share some feedback when you have the time - but no rush! Thanks :slightly_smiling_face:

**Comment by bernermic** [comment]
Hey chris,

thanks 🙏 I will test this some time soon and give you feedback.

**Comment by chrisallenlane** [comment]
Sounds great, @bernermic. Thanks!

**Pull request closed without merging**
