### PR TITLE
use `appdirs` to support platform depended data directories

### PR DESCRIPTION
**Pull request by brutus**
Sorry for another pull request… I had some problems while trying to rebase my old branch cleanly; probably the same you had while trying to merge it. So here's a clean new one — same changes, fresh base.

So, I guess this supersedes https://github.com/chrisallenlane/cheat/pull/243

### CODE REVIEW

**Comment by chrisallenlane** [comment]
Likewise, sorry for continuing to drag my feet here. I just want to take a minute to let you know what I'm thinking.

I definitely want to merge this in, however, I think that this will be a `major` release, in that it's going to change the prior default behavior (given that the default cheatsheet location will change.) I also think this commit may likely constitute the last `major` release this project ever sees, because realistically, `cheat` is a simple program, and already fulfills most of its goals. (I believe there will be other features merged looking at the open tickets we have, but they all seem to be backward-compatible feature additions - so, `minor` releases.)

With that said - and even though this is not _strictly_ necessary - I'm hoping to at least make some progress on #17 (Implement Unit Tests) before merging this in, just because we have quite a few people using this now (yay!), and I feel obligated to test rigorously before making `major` changes.

(Please don't take that as any sort of lack of confidence in your PR, of course. Rather, I'm just trying to be disciplined with regards to due-diligence here, even though I'm confident that I could just merge this without worry.)

So the bottleneck here is my relative ignorance regarding Python. (I'm a professional programmer, but not a Python programmer.) I'm not sure what best-practices are with regards to writing tests.

I'm optimistic that I'll be able to block out some time in the next week or two to educate myself, however. In the meantime, if anyone from among the community has time to address unit-tests, that would work too! :smile:

**Comment by jcrben** [comment]
It looks like this doesn't handle XDG_CONFIG_DIR and other XDG directories and instead forces users to set a new unique environment variable `DEFAULT_CHEAT_DIR`? If so, I think this should be revisited rather than merged in.

**Comment by brutus** [comment]
Yes, as far as I see it, all the `XDG_…` environment variables are only used on Linux systems and completely ignored on all other systems. This is working as intended I suppose. The `site_config_dir` path on Mac OS X is the same as `site_data_dir`, because there seems to be no distinction on that system.

I like your feature request on _appdirs_ though, and I think that this special case should be handled there and not in _cheat_.

The `DEFAULT_CHEAT_DIR` environment variable is nothing specific to this pull request, but instead is used by _cheat_ for a long time and should work under Mac OS X too.

**Comment by chrisallenlane** [comment]
@brutus, thanks for your work here, and sorry for never merging it in.

Python was causing us all kind of headaches, so I re-implemented `cheat` from scratch in Go. The new version is `v3`, which I released a moment ago.

If you were still struggling with this problem, please give the new version a try. I believe it should definitively solve your problem, and it adds a bunch of often-requested features as well.

**Pull request closed without merging**
