### PR TITLE
Fix problem that still edit the cheatsheet which not in the default_path.

### PR DESCRIPTION
**Pull request by roachsinai**
https://github.com/roachsinai/cheat/blob/0d82f1aae93386c353b1633d3cf0dcb7b06f74cb/cheat/sheet.py#L50

The line above still open the cheatsheet exists but not in the default_path.

### CODE REVIEW

**Comment by geeanlooca** [comment]
I can confirm. I just started using `cheat` today and I noticed that when I try to edit an already existing cheat it opens the wrong version in my editor, i.e. `cheat -e tmux` opens `/usr/share/cheat/tmux` so I can't save my changes. A copy of the cheat is correctly placed in my `.cheat` after I close the editor, however.

**Comment by sevens-ef** [comment]
I can confirm both the issue and this fix as well.

Steps to reproduce:
  * `cheat -e some_default_cheat_that_hasnt_been_edited_yet`
    * I.e. this needs to be a sheet that exists in `$CHEAT_PATH`, but *not* in `$CHEAT_USER_DIR`
  * Make some modifications
  * `cheat some_default_cheat_that_hasnt_been_edited_yet`
    * Output does not show the modifications that were made
  * `cheat -e some_default_cheat_that_hasnt_been_edited_yet`
  * Make new modifications
  * `cheat some_default_cheat_that_hasnt_been_edited_yet`
    * Output now *does* show the modifications (made in the last edit)

**Comment by chrisallenlane** [comment]
@roachsinai 

Thanks for your work here, and sorry that this never got merged in.

The Python version of `cheat` was causing us all sorts of headaches, so I re-implemented `cheat` from scratch in Go. (I released it moments ago as v3.) That being the case, I'm going to close this PR, as it's now moot.

With that said, please upgrade to v3 if you're able, and let me know if you encounter any issues. This should be solved in the new implementation.

Thanks.

**Comment by roachsinai** [comment]
Okay, glad to hear that!

**Pull request closed without merging**
