### PR TITLE
Created a `comm` cheatsheet

### PR DESCRIPTION
**Pull request by bannmann**

### CODE REVIEW

**Comment by chrisallenlane** [comment]
Also: sorry it has taken me so long to get to this!

**Comment by bannmann** [comment]
hi @chrisallenlane! it seems that on July 2nd, you wanted to merge this along with the other PRs. here's a gentle reminder to actually do it :-)

**Comment by chrisallenlane** [comment]
@bannmann 

I want to loop back on this.

I'm not sure if you noticed, but I opened a code-review on this a while ago. Please take a look at my questions, and I'd be happy to merge this :slightly_smiling_face: 

One note, though: I'm going to close this PR and ask you to open another.

If you take a look at #470, you'll notice that I externalized cheatsheets into their own repository with the v3 Go rewrite. With that said, when you have a moment, please open a pull-request against the new repository:

https://github.com/cheat/cheatsheets

Thanks!

**Comment by bannmann** [comment]
> please open a pull-request against the new repository

Done: https://github.com/cheat/cheatsheets/pull/1

**Pull request closed without merging**
