### PR TITLE
Adds some git helper scripts

### PR DESCRIPTION
**Pull request by bernermic**
Hey @chrisallenlane,

I made a stab at the scripting aproach to maintain cheatsheets in git repositories. 

This is a simple script which pulls/pushes all git maintained repo's by using `cheat -d`'s output ...

What do you think about this? 

Greetings

### CODE REVIEW

**Review by chrisallenlane — COMMENTED** [review]
I have a nit to pick, but these look great in general :+1:

**Comment by chrisallenlane** [comment]
Hey, @bernermic

Thanks for these! They work great. :partying_face: 

Regarding the packaging of these:

Do you think it would be worth combining these into a single executable? Maybe a `cheatsheets` executable, which would accept `push` and `pull` subcommands? Something like:

```sh
# pull from upstream
cheatsheets pull

# push to upstream
cheatsheets push
```

The advantage of that approach would be that we've have a single script that users could place on their `PATH`, and it would have a mostly sensible name.

The downside of that approach would be that we're making some assumptions regarding how users would want to use these scripts, and perhaps those assumptions are not correct.

I don't feel terribly strongly about this either way, but I'm curious what you think.

Question: how are you using these on your own machine? Do you just `cd` into your locally-cloned `cheat` repository and run them from `./scripts`, or do you have these placed directly on your `PATH`?

**Comment by bernermic** [comment]
@chrisallenlane glad to hear that they are of help. Actually atm. I only use the pull script and this is added to the PATH, but you are right.
Having them in one script seems a better option.

I will change the remarks you mentioned and come back to you. Right now I am quite busy, so let's see when I have time.

I would also write a section in the README on how to use.

**Comment by chrisallenlane** [comment]
Sounds great, @bernermic. Thanks! :slightly_smiling_face:

**Comment by bernermic** [comment]
Hi @chrisallenlane,

I modified the script now to have one file. As installation path I decided to use `~/.local/bin` as all distros with systemd should have this path out of the box added to `$PATH`.

Greetings

**Comment by bernermic** [comment]
Hi @chrisallenlane I made a single commit. Does this look fine now?

Greetings

**Comment by chrisallenlane** [comment]
This is perfect. Thanks so much! :partying_face:

**Pull request merged**
